# Generated by Django 4.1.2 on 2023-10-15 13:33

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_url', models.URLField(max_length=20, unique=True, validators=[django.core.validators.URLValidator()])),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='site_name')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_sites', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SiteStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clicks_number', models.PositiveIntegerField(default=0)),
                ('data_size', models.PositiveIntegerField(default=0)),
                ('site', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='statistics', to='user_site.usersite')),
            ],
        ),
    ]
