# Generated by Django 4.1.2 on 2023-03-24 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_alter_company_email_alter_company_legal_name_and_more'),
        ('location', '0003_rename_actual_address_location_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='address', to='company.address'),
        ),
    ]
