# Generated by Django 4.1.2 on 2023-03-30 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0002_auto_20230328_2049'),
        ('image', '0003_auto_20230328_2129'),
        ('location', '0005_alter_location_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='logo',
        ),
        migrations.RemoveField(
            model_name='location',
            name='url_height',
        ),
        migrations.RemoveField(
            model_name='location',
            name='url_width',
        ),
    ]
