# Generated by Django 4.1.2 on 2023-04-01 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0008_alter_company_logo'),
        ('location', '0007_location_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location', to='company.company'),
        ),
    ]
