# Generated by Django 4.1.2 on 2023-04-01 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0006_alter_image_image'),
        ('location', '0008_alter_location_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='logo',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='location_logo', to='image.image'),
        ),
    ]
