# Generated by Django 4.1.2 on 2023-04-11 16:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0009_alter_location_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='code',
            field=models.UUIDField(db_index=True, default=uuid.uuid4),
        ),
        migrations.AddField(
            model_name='location',
            name='menu',
            field=models.URLField(default='http://127.0.0.1:8000/menu/<django.db.models.fields.UUIDField>', verbose_name='location_menu'),
        ),
    ]
