# Generated by Django 4.1.2 on 2023-04-12 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0010_location_code_location_menu'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='menu',
        ),
    ]
