version: "3.9"
services:
  web:
    build:
      context: .
      dockerfile: Docker/web/Dockerfile
    ports:
      - 8000:8000
    volumes:
      - .:/WEB_menu_docker # local directory : container directory
#    environment:   # To set env data if it are not defined in the /Web_Menu_DA/.env.docker
#      - POSTGRES_HOST=db
    env_file:
      - Docker/.env.docker
    depends_on:
      - db
      - redis_app
  db:
#    image: postgres:13   # to start db without Dockerfile. disable next 3 rows
    build:
      context: .
      dockerfile: Docker/db/Dockerfile
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - Docker/.env.docker
    ports:
      - 5433:5432  # local port : container port
    expose:
      - 5432

  adminer: # docker with program adminer. It is app for web access to DB Postgres
#    image: adminer:4.8.1   # to start db without Dockerfile. disable next 3 rows
    build:
      context: .
      dockerfile: Docker/adminer/Dockerfile
    restart: always
#    environment:     # to set env without Dockerfile. disable env in Dockerfile_adminer
#      ADMINER_DEFAULT_SERVER: db
    depends_on:
      - db
    ports:
      - 8081:8080

  redis_app:
    build:
      context: .
      dockerfile: Docker/Redis/Dockerfile
    ports:
      - "6379:6379"

volumes:
  postgres_data:
