version: '3.9'
services:
  web:
    build:
      context: .
      dockerfile: Docker/web/Dockerfile
    command:
      - /bin/sh
      - -c
      - |
        python manage.py collectstatic --noinput
        python manage.py makemigrations
        python manage.py migrate
        echo "from registration.models import WebUser; WebUser.objects.filter(email='1234567899@admin.com').exists() or WebUser.objects.create_superuser(email='1234567899@admin.com', mobile_phone='+380634444444', password='$DJANGO_SUPERUSER_PASSWORD')" | python manage.py shell
        echo "from user_site.models import UserSite; UserSite.objects.filter(name='espreso').exists() or UserSite.objects.create(name='espreso', site_url='https://espreso.tv/', owner_id=1)" | python manage.py shell
        python manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000
    volumes:
      - .:/vpn_service
    env_file:
      - .env
    depends_on:
      - db

  db:
    build:
      context: .
      dockerfile: Docker/db/Dockerfile
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
    ports:
      - 5433:5432  # local port : container port
    expose:
      - 5432

  adminer:
    build:
      context: .
      dockerfile: Docker/adminer/Dockerfile
    restart: always
    depends_on:
      - db
    ports:
      - 8081:8080

volumes:
  postgres_data:
