version: "3.9"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.development
    ports:
      - 8000:8000
    volumes:
      - .:/WEB_menu_docker # local directory : container directory
#    environment:   # To set env data if it are not defined in the /Web_Menu_DA/.env.docker
#      - POSTGRES_HOST=db
    env_file:
      - Web_Menu_DA/.env.docker
    depends_on:
      - db
  db:
#    image: postgres:13   # to start db without Dockerfile. disable next 3 rows
    build:
      context: .
      dockerfile: Dockerfile_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - Web_Menu_DA/.env.docker
    ports:
      - 5433:5432  # local port : container port
    expose:
      - 5432

  adminer: # docker with program adminer. It is app for web access to DB Postgres
    image: adminer:4.8.1
    restart: always
    environment:
      ADMINER_DEFAULT_SERVER: db
    depends_on:
      - db
    ports:
      - 8081:8080

volumes:
  postgres_data:
