# Generated by Django 4.1.2 on 2023-04-06 15:42

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import re


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('image', '0006_alter_image_image'),
        ('location', '0009_alter_location_logo'),
        ('company', '0008_alter_company_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, verbose_name='name')),
                ('description', models.CharField(max_length=30, verbose_name='description')),
                ('volume', models.CharField(max_length=4, validators=[django.core.validators.RegexValidator(re.compile('^-?\\d+\\Z'), code='invalid', message='Enter a valid integer.')], verbose_name='volume')),
                ('measure', models.CharField(max_length=3, verbose_name='measure')),
                ('cost', models.CharField(max_length=4, validators=[django.core.validators.RegexValidator(re.compile('^-?\\d+\\Z'), code='invalid', message='Enter a valid integer.')], verbose_name='volume')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='company.company')),
                ('location', models.ManyToManyField(related_name='location_product', to='location.location')),
                ('logo', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_logo', to='image.image')),
            ],
        ),
    ]
