# Generated by Django 4.1.2 on 2023-04-08 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0009_alter_location_logo'),
        ('product', '0002_product_created_date_alter_product_cost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='location',
        ),
        migrations.AddField(
            model_name='product',
            name='locations',
            field=models.ManyToManyField(related_name='product_location', to='location.location'),
        ),
    ]
