# Generated by Django 4.1.2 on 2023-04-10 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_remove_product_location_product_locations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='measure',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Milligrams'), (1, 'Grams'), (2, 'Pieces')], verbose_name='measure'),
        ),
    ]
