# Generated by Django 4.1.2 on 2023-04-14 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_product_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.AlterField(
            model_name='product',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='cost'),
        ),
        migrations.AlterField(
            model_name='product',
            name='volume',
            field=models.PositiveSmallIntegerField(default=0, max_length=5, verbose_name='volume'),
        ),
    ]
