# Generated by Django 4.1.2 on 2023-04-14 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_remove_product_price_alter_product_cost_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='volume',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='volume'),
        ),
    ]
