# Generated by Django 4.1.2 on 2023-03-28 17:49

import company.business_logic
from django.db import migrations, models
import image


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_height', models.PositiveIntegerField(blank=True, null=True)),
                ('url_width', models.PositiveIntegerField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, height_field='url_height', null=True, upload_to=image.models.user_directory_path, validators=[company.business_logic.validate_image_size], width_field='url_width')),
                ('company', models.ForeignKey('company.Company', related_name='image_tmp', on_delete=models.DO_NOTHING, null=True)),
                ('location', models.ForeignKey('location.Location', related_name='image_tmp', on_delete=models.DO_NOTHING, null=True)),
            ],
        ),
    ]
