# Generated by Django 4.1.2 on 2023-03-30 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0004_update_image_ids'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='company',
        ),
        migrations.RemoveField(
            model_name='image',
            name='location',
        ),
    ]
