# Generated by Django 4.1.2 on 2023-01-25 21:42

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationTry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(db_index=True, error_messages={'unique': 'Not a valid email. Enter again and correctly.'}, max_length=254, unique=True)),
                ('code', models.UUIDField(db_index=True, default=uuid.uuid4)),
                ('creation_time', models.DateTimeField(auto_now=True)),
                ('confirmation_time', models.DateTimeField(null=True)),
            ],
        ),
    ]
