# Generated by Django 4.1.2 on 2023-02-08 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webmenuuser',
            name='passport_date_of_issue',
            field=models.DateField(null=True, verbose_name='passport date of issue'),
        ),
    ]
