# Generated by Django 4.1.2 on 2023-06-29 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_alter_webmenuuser_passport_date_of_issue'),
    ]

    operations = [
        migrations.AddField(
            model_name='webmenuuser',
            name='type_2fa',
            field=models.CharField(choices=[('', 'Disable'), ('Email', 'Email'), ('GoogleAuth', 'Googleauth')], default='', max_length=10, verbose_name='type_2fa'),
        ),
    ]
