# Generated by Django 4.1.2 on 2023-03-28 16:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('company', '0004_alter_company_actual_address_and_more'),
        ('address', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL("""
                INSERT INTO address_address (
                    id,
                    country,
                    city,
                    street,
                    house_number,
                    flat_number
                )
                SELECT
                    id,
                    country,
                    city,
                    street,
                    house_number,
                    flat_number
                FROM
                    company_address;
            """)
    ]
