# Generated by Django 4.1.2 on 2023-03-08 11:11

import company.business_logic
import image
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import phonenumber_field.modelfields
import re


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=30, verbose_name='legal country')),
                ('city', models.CharField(max_length=30, verbose_name='legal city')),
                ('street', models.CharField(max_length=50, verbose_name='legal street')),
                ('house_number', models.CharField(max_length=10, verbose_name='legal house number')),
                ('flat_number', models.CharField(max_length=10, verbose_name='legal flat number')),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_height', models.PositiveIntegerField(blank=True, null=True)),
                ('url_width', models.PositiveIntegerField(blank=True, null=True)),
                ('logo', models.ImageField(blank=True, height_field=models.PositiveIntegerField(blank=True, null=True), null=True, upload_to=image.models.user_directory_path, validators=[company.business_logic.validate_image_size], width_field=models.PositiveIntegerField(blank=True, null=True))),
                ('legal_name', models.CharField(max_length=50, verbose_name='legal_name')),
                ('code_USREOU', models.CharField(max_length=10, unique=True, validators=[django.core.validators.MinLengthValidator(8), django.core.validators.RegexValidator(re.compile('^-?\\d+\\Z'), code='invalid', message='Enter a valid integer.')], verbose_name='code USREOU')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(db_index=True, error_messages={'unique': 'Not a valid mobile phone. Enter again and correctly.'}, max_length=13, region='UA', unique=True)),
                ('email', models.EmailField(db_index=True, error_messages={'unique': 'Not a valid email. Enter again and correctly.'}, max_length=254, unique=True, verbose_name='email address')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('actual_address', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='actual_company', to='company.address')),
                ('legal_address', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='legal_company', to='company.address')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='company', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
