# Generated by Django 4.1.2 on 2023-03-24 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_alter_company_email_alter_company_legal_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='actual_address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='actual_address', to='company.address'),
        ),
        migrations.AlterField(
            model_name='company',
            name='legal_address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='legal_address', to='company.address'),
        ),
    ]
