# Generated by Django 4.1.2 on 2023-03-28 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0002_auto_20230328_1911'),
        ('location', '0005_alter_location_address'),
        ('company', '0004_alter_company_actual_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='actual_address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actual_address', to='address.address'),
        ),
        migrations.AlterField(
            model_name='company',
            name='legal_address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legal_address', to='address.address'),
        ),
    ]
