# Generated by Django 4.1.2 on 2023-03-30 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_alter_company_actual_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='logo',
        ),
        migrations.RemoveField(
            model_name='company',
            name='url_height',
        ),
        migrations.RemoveField(
            model_name='company',
            name='url_width',
        ),
    ]
