# Generated by Django 4.1.2 on 2023-04-01 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0006_alter_image_image'),
        ('company', '0007_company_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_logo', to='image.image'),
        ),
    ]
